# theme/theme.conf is generated from here — the colours come from ddlc-palette, the paper
# from ddlc-themes, the rest is the theme's own. The result is committed so the theme still
# installs with a plain cp; CI regenerates it and diffs, so the committed copy cannot drift
# from either
{
  lib,
  ddlc,
  roles,
}:

let
  inherit (ddlc) palette;

  # The polka-dot paper, as ddlc-themes defines it for every DDLC surface. The login screen
  # has one variant, the light one
  paper = {
    bgColor = roles.light.ground;
    dotColor = roles.light.dots;
  };

  # theme.conf key -> palette name
  colours = {
    accentPink = "pink";
    deepPink = "plum";
    # Both tones of Sayori's bow: the fill for the error line, the shade for the dots
    corruptDot = "bowShadow";
    textDark = "ink";
    textLight = "paper";
    errorRed = "bow";
    panelColor = "paper";
    panelBorder = "blush";
    okOutline = "plum";
    placeholderColor = "jacket";
    rowHighlight = "dot";
    # RGB-split: the two ends of the palette, warm against cool
    splitWarm = "bow";
    splitCool = "sayoriEye";
    # Scanlines over a glitch — two bright, one dark enough to read as a hole
    glitchPink = "pink";
    glitchCyan = "sayoriEye";
    glitchDark = "yuriShadow";
  };

  # Everything the palette has no opinion about
  own = {
    font = "Doki";
    iconFont = "DepartureMono Nerd Font";
    # Outline under the corrupted text: the palette's black at a quarter, in Qt's own spelling
    corruptOutline = ddlc.argb.ink "0.25";
    scrollDuration = 14000;
    glitchRgbSplit = true;
  };

  render = k: v: "${k}=${lib.generators.mkValueStringDefault { } v}";

  # Order is deliberate: fonts, then colours, then geometry and behaviour
  lines = [
    (render "font" own.font)
    (render "iconFont" own.iconFont)
  ]
  ++ lib.mapAttrsToList render paper
  ++ lib.mapAttrsToList (k: name: render k palette.${name}) colours
  ++ [
    (render "corruptOutline" own.corruptOutline)
    # The paper's tile, which holds two dots, and their radius
    (render "dotSpacing" roles.polka.tile)
    (render "dotRadius" roles.polka.dot)
    (render "scrollDuration" own.scrollDuration)
    (render "glitchRgbSplit" own.glitchRgbSplit)
  ];
in
''
  ; DDLC theme settings: palette, fonts and animation speeds.
  ; Read in QML via config.<key> (all values are strings)
  ;
  ; Generated by nix/theme-conf.nix — the colours come from github:rokokol/ddlc-palette,
  ; the dots and the ground under them from github:rokokol/ddlc-themes.
  ; Change them there, or per-machine through ddlc.sddm.settings on NixOS
  [General]
  ${lib.concatStringsSep "\n" lines}
''
