# theme/theme.conf is generated from here — the colours come from ddlc-palette, the rest is
# the theme's own. The result is committed so the theme still installs with a plain cp; CI
# regenerates it and diffs, so the committed copy cannot drift from the palette
{ lib, palette }:

let
  # theme.conf key -> palette name
  colours = {
    bgColor = "paper";
    accentPink = "pink";
    deepPink = "plum";
    dotColor = "dot";
    # Both tones of Sayori's bow: the fill for the error line, the shade for the dots
    corruptDot = "bowShadow";
    textDark = "ink";
    textLight = "paper";
    errorRed = "bow";
    panelColor = "paper";
    panelBorder = "blush";
    okOutline = "plum";
    placeholderColor = "jacket";
    rowHighlight = "dot";
    # RGB-split: the two ends of the palette, warm against cool
    splitWarm = "bow";
    splitCool = "sayoriEye";
    # Scanlines over a glitch — two bright, one dark enough to read as a hole
    glitchPink = "pink";
    glitchCyan = "sayoriEye";
    glitchDark = "yuriShadow";
  };

  # Everything the palette has no opinion about
  own = {
    font = "Doki";
    iconFont = "DepartureMono Nerd Font";
    # An alpha, which no palette entry carries: the corrupted text is outlined by a shadow
    corruptOutline = "#40000000";
    dotSpacing = 200;
    dotRadius = 40;
    scrollDuration = 14000;
    glitchRgbSplit = true;
  };

  render = k: v: "${k}=${lib.generators.mkValueStringDefault { } v}";

  # Order is deliberate: fonts, then colours, then geometry and behaviour
  lines = [
    (render "font" own.font)
    (render "iconFont" own.iconFont)
  ]
  ++ lib.mapAttrsToList (k: name: render k palette.${name}) colours
  ++ [
    (render "corruptOutline" own.corruptOutline)
    (render "dotSpacing" own.dotSpacing)
    (render "dotRadius" own.dotRadius)
    (render "scrollDuration" own.scrollDuration)
    (render "glitchRgbSplit" own.glitchRgbSplit)
  ];
in
''
  ; DDLC theme settings: palette, fonts and animation speeds.
  ; Read in QML via config.<key> (all values are strings)
  ;
  ; Generated by nix/theme-conf.nix — the colours come from github:rokokol/ddlc-palette.
  ; Change them there, or per-machine through ddlc.sddm.settings on NixOS
  [General]
  ${lib.concatStringsSep "\n" lines}
''
